import pandas as pd

df = pd.read_csv("data/raw/APL_Logistics.csv", encoding="latin1")

print("=" * 60)
print("1. DATA CLEANING & FINANCIAL VALIDATION")
print("=" * 60)
print(f"Total records: {len(df)}")
print(f"Missing values:\n{df.isnull().sum()[df.isnull().sum() > 0]}")
print(f"Zero sales records: {(df['Sales'] == 0).sum()}")
print(f"Zero profit records: {(df['Order Profit Per Order'] == 0).sum()}")

print("\n" + "=" * 60)
print("2. REVENUE & PROFIT OVERVIEW")
print("=" * 60)
print(f"Total Revenue: ${df['Sales'].sum():,.2f}")
print(f"Total Profit: ${df['Order Profit Per Order'].sum():,.2f}")
print(f"Overall Profit Margin: {(df['Order Profit Per Order'].sum() / df['Sales'].sum()) * 100:.2f}%")

print("\n" + "=" * 60)
print("3. PRODUCT & CATEGORY PROFITABILITY")
print("=" * 60)
print("\nTop 5 Products by Profit:")
print(df.groupby("Product Name")["Order Profit Per Order"].sum().sort_values(ascending=False).head())
print("\nBottom 5 Loss-Making Products:")
print(df.groupby("Product Name")["Order Profit Per Order"].sum().sort_values().head())
print("\nProfit by Category:")
print(df.groupby("Category Name")["Order Profit Per Order"].sum().sort_values(ascending=False))

print("\n" + "=" * 60)
print("4. CUSTOMER CONTRIBUTION ANALYSIS")
print("=" * 60)
print(f"Total Unique Customers: {df['Customer Id'].nunique()}")
print("\nTop 5 High-Value Customers:")
print(df.groupby("Customer Id")["Order Profit Per Order"].sum().sort_values(ascending=False).head())
print("\nBottom 5 Loss-Making Customers:")
print(df.groupby("Customer Id")["Order Profit Per Order"].sum().sort_values().head())

print("\n" + "=" * 60)
print("5. DISCOUNT IMPACT DIAGNOSTICS")
print("=" * 60)
print(f"Average Discount Rate: {df['Order Item Discount Rate'].mean():.2%}")
print(f"Avg Profit Margin WITH discount: {df[df['Order Item Discount Rate'] > 0]['Order Item Profit Ratio'].mean():.2%}")
print(f"Avg Profit Margin WITHOUT discount: {df[df['Order Item Discount Rate'] == 0]['Order Item Profit Ratio'].mean():.2%}")

print("\n" + "=" * 60)
print("6. MARKET & REGIONAL PROFIT ANALYSIS")
print("=" * 60)
print("\nProfit by Market:")
print(df.groupby("Market")["Order Profit Per Order"].sum().sort_values(ascending=False))
print("\nProfit by Region:")
print(df.groupby("Order Region")["Order Profit Per Order"].sum().sort_values(ascending=False))
print("\nProfit by Country:")
print(df.groupby("Order Country")["Order Profit Per Order"].sum().sort_values(ascending=False).head(10))